// Hardware project data for Hardware.vue
// Each project supports these fields:
//   date      Date
//   title     string
//   text      string        — short description shown on card & modal
//   details   string        — longer write-up shown only in the modal (optional)
//   img       string|array  — single path or array of paths (images + .mp4/.webm)
//   category  "embedded" | "iot" | "led" | "audio" | "radio" | "pcb"
//   tech      string[]      — tech stack chips
//   repo      string        — GitHub URL (optional)
//   link      string        — live/demo URL (optional)
//   gerbers   string        — Gerber download URL (optional)
//   bom       string        — BOM download URL (optional)

export const projects = [
  {
    date: new Date("Feb 20, 2026"),
    title: "Hyphea Duo PCB",
    text: "Dual LED strip driver and battery charger hat for XIAO. I2C broken out to add an IMU later for motion-reactive effects.",
    details: "",
    img: "/images/hardware/Hyphae-Duo.jpg",
    category: "led",
    tech: ["LED", "XIAO"],
  },
  {
    date: new Date("Feb 16, 2026"),
    title: "POV POI",
    text: "Persistence of Vision (POV) creates patterns in the air when spun. An updated version of the Light Tube Art Piece concept, this handheld version is designed to be spun like a poi for dynamic light patterns. Powered by an ESP32 and SK6812 LEDs.",
    details: "",
    img: "/images/hardware/POV_POI.jpg",
    category: "led",
    tech: ["LED", "SK6812", "ESP32", "POV"],
  },
  {
    date: new Date("Feb 3, 2026"),
    title: "Smart Sprout V1",
    text: "A sprout clip with a tetrahedral LED array on top, powered by an Artemis Redboard Nano and a recovered vape battery. Bluetooth controls.",
    details: "",
    img: ["/images/hardware/smart-sprout_v1.mp4", "/images/hardware/smart_sprout-V1.jpg", "/images/hardware/artemis_vape_batt.mp4"],
    category: "led",
    tech: ["LED", "Artemis", "Bluetooth", "Vape Battery"],
  },
  {
    date: new Date("Jan 18, 2026"),
    title: "WLED Panel",
    text: "An array of WS2812B LEDs controlled by WLED firmware running on an ESP32.",
    details: "",
    img: ["/images/hardware/WLED-Panel.mp4", "/images/hardware/WLED-Panel.png"],
    category: "led",
    tech: ["WS2812B", "WLED", "ESP32"],
  },
  {
    date: new Date("Jan 8, 2026"),
    title: "Light Tube Art Piece",
    text: "A 3D printed light with 2 WS2812B LED strips driven by an ESP32 and powered by an 18650 Li-Ion battery. Bluetooth controls.",
    details: "",
    img: ["/images/hardware/Light_tube.mp4", "/images/hardware/LightTube.png"],
    category: "led",
    tech: ["LED", "Bluetooth", "3D Printing", "18650 Battery"],
  },
  {
    date: new Date("Dec 20, 2025"),
    title: "Glow Flora Home V1",
    text: "Lily origami flowers sprouting from a flower pot with addressable LEDs, an 18650 battery, and an ESP32 controller. Running WLED.",
    details: "",
    img: "/images/hardware/Glow_Flora_Home-V1.png",
    category: "led",
    tech: ["LED", "ESP32", "18650 Battery", "WLED"],
  },
  {
    date: new Date("Aug 5, 2025"),
    title: "Glow Flora Clip",
    text: "An origami Lily with flexible LED filament powered from a coin cell.",
    details: "",
    img: "/images/hardware/Glow_Flora_Clip.jpg",
    category: "led",
    tech: ["LED", "Coin Cell"],
  },
  {
    date: new Date("March 15, 2025"),
    title: "Glow Flora Handheld V1",
    text: "An origami Lily with addressable LEDs driven by a XIAO ESP32-C6. USB C rechargeable Li-Po battery. The first in a line of handheld LED art pieces.",
    details: "",
    img: ["/images/hardware/Glow_Flora_Handheld-V1.jpg", "/images/hardware/LiPo_LED.jpg"],
    category: "led",
    tech: ["LED", "WS2812B", "ESP32-C6", "Li-Po", "USB C"],
  },
  {
    date: new Date("Oct 15, 2024"),
    title: "Phi Lamp",
    text: "A lamp designed with the golden spiral.",
    details: "",
    img: "/images/hardware/phi-lamp.jpg",
    category: "led",
    tech: ["LED", "USB"],
  },
  {
    date: new Date("Nov 28, 2023"),
    title: "Air Quality Monitor",
    text: "A unit of sensors to monitor air quality including particulate matter, CO₂, VOC, temperature and humidity. Built with an Artemis Redboard Nano. Read data over Bluetooth.",
    details: "",
    img: ["/images/hardware/air-quality-monitor.jpg", "/images/hardware/air-quality-monitor2.jpg", "/images/hardware/air-quality-monitor3.jpg"],
    category: "iot",
    tech: ["Artemis", "Bluetooth", "BME680", "PMS5003", "SGP30"],
  },
  {
    date: new Date("Feb 14, 2021"),
    title: "Physical NFT Prototype",
    text: "A prototype for a physical NFT using a Secure Element Chip to store cryptographic keys.",
    details: "",
    img: ["/images/hardware/nft-prototype.jpg", "/images/hardware/nft_proto2.jpg"],
    category: "embedded",
    tech: ["NFT", "Secure Element", "Crypto"],
  },
  {
    date: new Date("Oct 7, 2020"),
    title: "LED Lily Pyramid Base",
    text: "A custom 3D printed base to house the LED Lily Controller and LiPo battery, with integrated charging and power management.",
    details: "",
    img: "/images/hardware/pyramid-board.jpeg",
    category: "led",
    tech: ["Eagle", "LiPo", "TP4056"],
  },
  {
    date: new Date("October 26, 2019"),
    title: "Dual RGBW Strip ArtNet Controller",
    text: "A hand-soldered PCB to control two RGBW LED strips with an ESP8266, receiving DMX-over-IP for professional lighting control.",
    details: "",
    img: "/images/hardware/dual-rgbw-artnet.jpg",
    category: "led",
    tech: ["ESP8266", "ArtNet", "RGBW LEDs"],
  },
  {
    date: new Date("October 26, 2019"),
    title: "Flex Lily PCB",
    text: "A flex PCB to fit WS2812B-mini LEDs inside of an origami lily.",
    details: "",
    img: "",
    category: "led",
    tech: ["Origami", "RGB LEDs"],
  },
  {
    date: new Date("October 26, 2019"),
    title: "Touch n' Glow",
    text: "A PCB with capacitive touch pads, one WS2812B, and a 3.5mm port to connect RGB LEDs.",
    details: "",
    img: ["/images/hardware/TnG.jpg", "/images/hardware/touchnglow.jpg"],
    category: "led",
    tech: ["Capacitive Touch", "KiCad", "RGB LEDs"],
    repo: "https://github.com/skyfly200/touch-n-glow",
  },
  {
    date: new Date("Oct 18, 2019"),
    title: "Hexy Pix PCB",
    text: "A breakout board for WS2812B 5050 addressable LEDs in a hexagonal layout.",
    details: "",
    img: ["/images/hardware/hexypix.jpg", "/images/hardware/hexy.jpg", "/images/hardware/hexy3.jpg", "/images/hardware/hexy2.jpg"],
    category: "led",
    tech: ["WS2812B", "Eagle", "PCB"],
  },
  {
    date: new Date("August 26, 2019"),
    title: "Ill'uminator PCB",
    text: "My first designed and manufactured PCB! A basic RGB LED strip controller with sweet PCB art on the back. MOSFET-switched RGB channels, 12V input.",
    details: "",
    img: "/images/hardware/illuminator.jpg",
    category: "led",
    tech: ["MOSFET", "Eagle", "RGB", "12V"],
  },
  {
    date: new Date("July 2019"),
    title: "PT2399 Delay IC Echo Circuit",
    text: "Old-school bucket brigade delay IC circuit built around the PT2399, with adjustable delay time and feedback for guitar effects.",
    details: "",
    img: "",
    category: "audio",
    tech: ["PT2399", "Analog", "Guitar FX", "Through-hole"],
  },
  {
    date: new Date("March 15, 2019"),
    title: "ArtNet LED Strip Controller",
    text: "ArtNet WS2812b strip controller running on ESP32 Thing from SparkFun. Receives DMX-over-IP for professional lighting control.",
    details: "",
    img: "/images/hardware/ARTNET.png",
    category: "led",
    tech: ["ESP32", "ArtNet", "WS2812B", "DMX", "Wi-Fi"],
    repo: "https://github.com/skyfly200/Radio-Net-Hub",
  },
  {
    date: new Date("November 16, 2018"),
    title: "Tower of Power",
    text: "An animated LED art piece made with a laser-cut logo for our station backed with addressable LEDs. Running off a QT PY board from Adafruit.",
    details: "",
    img: ["/images/hardware/tower.jpg", "/images/hardware/TowerOfPower.mp4"],
    category: "radio",
    tech: ["CircuitPython", "WS2812B", "Laser Cut", "Li-Po"],
  },
  {
    date: new Date("November 1, 2018"),
    title: "Sparky — 150W FM Transmitter",
    text: "A 150W stereo FM transmitter with laser-cut front and rear panels to mount all the hardware in a spare PC case.",
    details: "",
    img: ["/images/hardware/sparky.jpg", "/images/hardware/sparky2.jpg"],
    category: "radio",
    tech: ["RF", "FM", "150W PA", "Laser Cut"],
  },
  {
    date: new Date("March 3, 2018"),
    title: "LED Lily Origami Fixture",
    text: "Origami flower modular LED fixture with embedded addressable LEDs, connects to a controller with a 3.5mm TRRS jack.",
    details: "",
    img: "/images/hardware/origami-lily.jpg",
    category: "led",
    tech: ["WS2812B", "Modular", "Origami"],
  },
  {
    date: new Date("March 2, 2018"),
    title: "Modular LED Controller",
    text: "ESP32 LED controller that connects to light fixtures via TRS jack. Bluetooth control with custom PWA app. Fully modular — one controller drives multiple fixtures.",
    details: "",
    img: "/images/hardware/esp32-pack.jpg",
    category: "led",
    tech: ["ESP32", "Bluetooth", "Modular", "Li-Po"],
    repo: "https://github.com/skyfly200/BLE-LED-PWA",
  },
  {
    date: new Date("Feb 4, 2018"),
    title: "LEGO DMX Moving Light",
    text: "A one-axis pan/tilt moving head light fixture made out of LEGO, with an Arduino Uno and a MAX485 breadboard circuit to receive DMX512 control signals.",
    details: "",
    img: "/images/hardware/DMX.jpg",
    category: "led",
    tech: ["DMX512", "Arduino", "LEGO", "MAX485"],
  },
  {
    date: new Date("Dec 25, 2017"),
    title: "LED Origami Rose",
    text: "Origami rose with embedded addressable LEDs, selectable animation modes, and micro-USB recharging. Built with an Arduino Pro Mini, a Li-Po battery, and a SparkFun charge controller / 5V boost module.",
    details: "",
    img: ["/images/hardware/rose.mp4", "/images/hardware/LED-Rose.jpg"],
    category: "led",
    tech: ["WS2812B", "Arduino", "LiPo", "USB Charging"],
  },
  {
    date: new Date("Dec 25, 2017"),
    title: "Light Painting Wand",
    text: "A string of addressable LEDs to light paint with, powered by an Arduino Pro Mini and a USB cable for power.",
    details: "",
    img: "",
    category: "led",
    tech: ["WS2812B", "Arduino", "USB Powered"],
    repo: "https://github.com/skyfly200/light-painting-wand",
  },
  {
    date: new Date("November 16, 2017"),
    title: "Animated Musical Note Light",
    text: "A musical note-shaped LED matrix.",
    details: "",
    img: "",
    category: "led",
    tech: ["Arduino", "WS2812B", "LED"],
    repo: "https://github.com/skyfly200/note-rainbow",
  },
  {
    date: new Date("Oct 27, 2017"),
    title: "Chasing EL Wire Vest",
    text: "Chasing EL wire vest with addressable LED belt pack. RJ45 expansion port for LEDs, buttons, and sensors.",
    details: "",
    img: "/images/hardware/EL_Vest.mp4",
    category: "led",
    tech: ["EL Wire", "WS2812B", "Arduino", "RJ45"],
    repo: "https://github.com/skyfly200/EL-Vest",
  },
  {
    date: new Date("Jan 29, 2017"),
    title: "TMP/RH PID Controller",
    text: "Arduino PID controller for temperature and humidity with LCD readout and light level sensor. Used for environmental control.",
    details: "",
    img: ["/images/hardware/PID.jpg", "/images/hardware/pid-controller.jpg"],
    category: "embedded",
    tech: ["Arduino", "PID", "DHT22", "LCD", "I2C"],
    repo: "https://github.com/skyfly200/PID-TMP-RH",
  },
  {
    date: new Date("Mar 8, 2014"),
    title: "80s Text-to-Speech Chip",
    text: "Arduino sketch for the SP0256A-AL2 IC manufactured in 1981, a vintage speech synthesis chip.",
    details: "",
    img: "/images/hardware/TTS-IC.jpg",
    category: "audio",
    tech: ["Arduino", "SP0256", "Vintage IC"],
    repo: "https://github.com/skyfly200/SP0256_AL2",
  },
  {
    date: new Date("June 2, 2013"),
    title: "Music Reactive LED Strip",
    text: "7-band audio reactive RGB LED strip controller driven by an Arduino.",
    details: "",
    img: "",
    category: "led",
    tech: ["Arduino", "LED"],
    repo: "https://github.com/skyfly200/MusicReactiveRGBStrip",
  },
  {
    date: new Date("May 2, 2013"),
    title: "Audio Spectrum Visualizer",
    text: "7-band graphic EQ chip hooked up to an Arduino, driving a shift register to PWM-control a row of LEDs to display the audio spectrum.",
    details: "",
    img: ["/images/hardware/HW-p1.jpg", "/images/hardware/msgeq7.JPG"],
    category: "audio",
    tech: ["Arduino", "MSGEQ7", "Shift Register", "PWM", "LED Matrix"],
  },
  {
    date: new Date("May 2, 2013"),
    title: "Wireless Weather Station",
    text: "Wireless Arduino weather station with temperature, humidity, and pressure sensors.",
    details: "",
    img: "/images/hardware/weather-station.jpg",
    category: "iot",
    tech: ["Arduino", "DHT22", "BMP180"],
    repo: "https://github.com/skyfly200/Wireless-Arduino-Weather-Station",
  },
];

export const stats = [
  { num: "14+", label: "Years Building" },
  { num: "34+", label: "Hardware Projects" },
  { num: "7",   label: "Custom PCBs Made" },
  { num: "∞",   label: "LEDs Driven" },
];